### ISSUE TITLE
.ini文件要怎么用?

### ISSUE THREAD

**Issue by Karmylr** [txyyh/ClashFiles#2]
如题

**Comment by txyyh** [comment]
作为外部配置使用

**Comment by txyyh** [comment]
![IMG_20210922_120934](https://user-images.githubusercontent.com/41893946/134282183-d715af95-13f1-4c73-a769-7dedcb5512f8.jpg)

**Comment by Karmylr** [comment]
0.7.0以上就不行了

**Comment by txyyh** [comment]
@Karmylr 
请清楚描述问题
本人使用 Clash For Windows 0.19.3 已经 Clash for Magisk (by manjusaka) 均正常
使用的是 ACL4SSR_Online_ownuse.ini

**Comment by Karmylr** [comment]
在在线订阅转换里的远程配置使用自己的ini的链接，生成的订阅链接打开后的配置文件，有时是应用了ini的，有时没有

**Comment by txyyh** [comment]
此问题请反馈给后端提供者
